library(ggplot2)

p <- ggplot(data.frame(x=1,y=1), aes(x,y)) +
geom_point(alpha=0) + theme_void()

## rissq ----
hexSticker::sticker(p,
                    package = "rissq",
                    spotlight = FALSE,
                    h_size = 2,
                    h_color = "gray",
                    h_fill = "firebrick",
                    p_size = 30,
                    p_y = 1,
                    # p_family = "RobotoCondensed-Regular",
                    s_x=1, s_y=0.95, s_width=0.96,
                    url="rissq.github.io",
                    u_size = 2,
                    u_y = 0.1,
                    u_color = "black",
                    filename="tools/rissq.png")
## rissq.spc ----
hexSticker::sticker(p,
                    package = ".spc",
                    spotlight = FALSE,
                    h_size = 2,
                    h_color = "gray",
                    h_fill = "deepskyblue",
                    p_size = 30,
                    p_y = 1,
                    # p_family = "RobotoCondensed-Regular",
                    s_x=1, s_y=0.95, s_width=0.96,
                    url="rissq.github.io",
                    u_size = 2,
                    u_y = 0.1,
                    u_color = "black",
                    filename="tools/rissq.spc.png")
## rissq.app ----
hexSticker::sticker(p,
                    package = ".app",
                    spotlight = FALSE,
                    h_size = 2,
                    h_color = "gray",
                    h_fill = "deepskyblue4",
                    p_size = 30,
                    p_y = 1,
                    # p_family = "RobotoCondensed-Regular",
                    s_x=1, s_y=0.95, s_width=0.96,
                    url="rissq.github.io",
                    u_size = 2,
                    u_y = 0.1,
                    u_color = "black",
                    filename="tools/rissq.app.png")
## rissq.msa ----
hexSticker::sticker(p,
                    package = ".msa",
                    spotlight = FALSE,
                    h_size = 2,
                    h_color = "gray",
                    h_fill = "gold3",
                    p_size = 30,
                    p_y = 1,
                    # p_family = "RobotoCondensed-Regular",
                    s_x=1, s_y=0.95, s_width=0.96,
                    url="rissq.github.io",
                    u_size = 2,
                    u_y = 0.1,
                    u_color = "black",
                    filename="tools/rissq.msa.png")
## rissq.data ----
hexSticker::sticker(p,
                    package = ".data",
                    spotlight = FALSE,
                    h_size = 2,
                    h_color = "gray",
                    h_fill = "snow4",
                    p_size = 30,
                    p_y = 1,
                    # p_family = "RobotoCondensed-Regular",
                    s_x=1, s_y=0.95, s_width=0.96,
                    url="rissq.github.io",
                    u_size = 2,
                    u_y = 0.1,
                    u_color = "black",
                    filename="tools/rissq.data.png")
## rissq.io ----
hexSticker::sticker(p,
                    package = ".io",
                    spotlight = FALSE,
                    h_size = 2,
                    h_color = "gray",
                    h_fill = "forestgreen",
                    p_size = 30,
                    p_y = 1,
                    # p_family = "RobotoCondensed-Regular",
                    s_x=1, s_y=0.95, s_width=0.96,
                    url="rissq.github.io",
                    u_size = 3,
                    u_y = 0.1,
                    u_color = "black",
                    filename="tools/rissq.io.png")
## rissq.acceptance ----
hexSticker::sticker(p,
                    package = ".as",
                    spotlight = FALSE,
                    h_size = 2,
                    h_color = "gray",
                    h_fill = "violet",
                    p_size = 30,
                    p_y = 1,
                    # p_family = "RobotoCondensed-Regular",
                    s_x=1, s_y=0.95, s_width=0.96,
                    url="rissq.github.io",
                    u_size = 3,
                    u_y = 0.1,
                    u_color = "black",
                    filename="tools/rissq.as.png")
